# Generated by Django 4.2.6 on 2023-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chapter',
            field=models.CharField(default='第一章', max_length=200),
        ),
    ]
