# Generated by Django 4.2.6 on 2023-10-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_post_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='who?', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
