# Generated by Django 4.2.6 on 2023-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_post_image_url_alter_post_body_alter_post_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Literature', '文學'), ('Light Novel', '輕小說'), ('History', '歷史'), ('Biography', '自傳'), ('Philosophy', '哲學')], default='類型?', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
